"""empty message

Revision ID: 0884f717c008
Revises: 6987e472d135
Create Date: 2018-06-19 23:37:54.751520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0884f717c008'
down_revision = '6987e472d135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('sort', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'sort')
    # ### end Alembic commands ###
